### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by XinhuaZhang** [tub-rip/event_based_optical_flow#17]
Hello, 

I wonder if this code supports training on custom dataset? I would like to train it on the Prophesee dataset. It seems that a lot of modifications are needed.

Thanks,

**Comment by shiba24** [comment]
Hi, you first need to convert data to HDF5 because currently .raw format is not supported.
Can you check another library that I have been developing?: https://github.com/shiba24/event-vision-library/tree/main
Example (from text to hdf5): https://github.com/shiba24/event-vision-library/blob/main/examples/convert_text_to_hdf5.py

My long-term plan is to develop the library and include some algorithms there.

**Comment by shiba24** [comment]
And after that you might want to write a custom data loader class for the Psee dataset. It's relatively straightforward and simple to implement it.
https://github.com/tub-rip/event_based_optical_flow/tree/main/src/data_loader
Actually I have one, but am not planning to release it anytime soon.

**Comment by XinhuaZhang** [comment]
> Hi, you first need to convert data to HDF5 because currently .raw format is not supported. Can you check another library that I have been developing?: https://github.com/shiba24/event-vision-library/tree/main Example (from text to hdf5): https://github.com/shiba24/event-vision-library/blob/main/examples/convert_text_to_hdf5.py
> 
> My long-term plan is to develop the library and include some algorithms there.

Thank you. I will try it.
